name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        working-directory: .
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$(basename ${{ github.repository }}):latest \
            --build-arg DB_HOST='${{ secrets.DB_HOST }}' \
            --build-arg DB_PORT='${{ secrets.DB_PORT }}' \
            --build-arg DB_DATABASE='${{ secrets.DB_DATABASE }}' \
            --build-arg DB_USERNAME='${{ secrets.DB_USERNAME }}' \
            --build-arg DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            .

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$(basename ${{ github.repository }}):latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Log in to Google Container Registry (GCR)
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Tag Docker image for Google Container Registry (GCR)
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/$(basename ${{ github.repository }}):latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/$(basename ${{ github.repository }}):latest

      - name: Push to Google Container Registry (GCR)
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$(basename ${{ github.repository }}):latest
